import type { Surah } from "../types/quran";

// Static data — all 114 surahs. Never changes, no network call needed.
export const SURAHS: Surah[] = [
  { number: 1, nameArabic: "الفاتحة", nameEnglish: "Al-Fatihah", englishMeaning: "The Opening", ayahCount: 7 },
  { number: 2, nameArabic: "البقرة", nameEnglish: "Al-Baqarah", englishMeaning: "The Cow", ayahCount: 286 },
  { number: 3, nameArabic: "آل عمران", nameEnglish: "Ali 'Imran", englishMeaning: "Family of Imran", ayahCount: 200 },
  { number: 4, nameArabic: "النساء", nameEnglish: "An-Nisa", englishMeaning: "The Women", ayahCount: 176 },
  { number: 5, nameArabic: "المائدة", nameEnglish: "Al-Ma'idah", englishMeaning: "The Table Spread", ayahCount: 120 },
  { number: 6, nameArabic: "الأنعام", nameEnglish: "Al-An'am", englishMeaning: "The Cattle", ayahCount: 165 },
  { number: 7, nameArabic: "الأعراف", nameEnglish: "Al-A'raf", englishMeaning: "The Heights", ayahCount: 206 },
  { number: 8, nameArabic: "الأنفال", nameEnglish: "Al-Anfal", englishMeaning: "The Spoils of War", ayahCount: 75 },
  { number: 9, nameArabic: "التوبة", nameEnglish: "At-Tawbah", englishMeaning: "The Repentance", ayahCount: 129 },
  { number: 10, nameArabic: "يونس", nameEnglish: "Yunus", englishMeaning: "Jonah", ayahCount: 109 },
  { number: 11, nameArabic: "هود", nameEnglish: "Hud", englishMeaning: "Hud", ayahCount: 123 },
  { number: 12, nameArabic: "يوسف", nameEnglish: "Yusuf", englishMeaning: "Joseph", ayahCount: 111 },
  { number: 13, nameArabic: "الرعد", nameEnglish: "Ar-Ra'd", englishMeaning: "The Thunder", ayahCount: 43 },
  { number: 14, nameArabic: "إبراهيم", nameEnglish: "Ibrahim", englishMeaning: "Abraham", ayahCount: 52 },
  { number: 15, nameArabic: "الحجر", nameEnglish: "Al-Hijr", englishMeaning: "The Rocky Tract", ayahCount: 99 },
  { number: 16, nameArabic: "النحل", nameEnglish: "An-Nahl", englishMeaning: "The Bee", ayahCount: 128 },
  { number: 17, nameArabic: "الإسراء", nameEnglish: "Al-Isra", englishMeaning: "The Night Journey", ayahCount: 111 },
  { number: 18, nameArabic: "الكهف", nameEnglish: "Al-Kahf", englishMeaning: "The Cave", ayahCount: 110 },
  { number: 19, nameArabic: "مريم", nameEnglish: "Maryam", englishMeaning: "Mary", ayahCount: 98 },
  { number: 20, nameArabic: "طه", nameEnglish: "Ta-Ha", englishMeaning: "Ta-Ha", ayahCount: 135 },
  { number: 21, nameArabic: "الأنبياء", nameEnglish: "Al-Anbiya", englishMeaning: "The Prophets", ayahCount: 112 },
  { number: 22, nameArabic: "الحج", nameEnglish: "Al-Hajj", englishMeaning: "The Pilgrimage", ayahCount: 78 },
  { number: 23, nameArabic: "المؤمنون", nameEnglish: "Al-Mu'minun", englishMeaning: "The Believers", ayahCount: 118 },
  { number: 24, nameArabic: "النور", nameEnglish: "An-Nur", englishMeaning: "The Light", ayahCount: 64 },
  { number: 25, nameArabic: "الفرقان", nameEnglish: "Al-Furqan", englishMeaning: "The Criterion", ayahCount: 77 },
  { number: 26, nameArabic: "الشعراء", nameEnglish: "Ash-Shu'ara", englishMeaning: "The Poets", ayahCount: 227 },
  { number: 27, nameArabic: "النمل", nameEnglish: "An-Naml", englishMeaning: "The Ant", ayahCount: 93 },
  { number: 28, nameArabic: "القصص", nameEnglish: "Al-Qasas", englishMeaning: "The Stories", ayahCount: 88 },
  { number: 29, nameArabic: "العنكبوت", nameEnglish: "Al-'Ankabut", englishMeaning: "The Spider", ayahCount: 69 },
  { number: 30, nameArabic: "الروم", nameEnglish: "Ar-Rum", englishMeaning: "The Romans", ayahCount: 60 },
  { number: 31, nameArabic: "لقمان", nameEnglish: "Luqman", englishMeaning: "Luqman", ayahCount: 34 },
  { number: 32, nameArabic: "السجدة", nameEnglish: "As-Sajdah", englishMeaning: "The Prostration", ayahCount: 30 },
  { number: 33, nameArabic: "الأحزاب", nameEnglish: "Al-Ahzab", englishMeaning: "The Combined Forces", ayahCount: 73 },
  { number: 34, nameArabic: "سبأ", nameEnglish: "Saba", englishMeaning: "Sheba", ayahCount: 54 },
  { number: 35, nameArabic: "فاطر", nameEnglish: "Fatir", englishMeaning: "Originator", ayahCount: 45 },
  { number: 36, nameArabic: "يس", nameEnglish: "Ya-Sin", englishMeaning: "Ya Sin", ayahCount: 83 },
  { number: 37, nameArabic: "الصافات", nameEnglish: "As-Saffat", englishMeaning: "Those Ranged in Ranks", ayahCount: 182 },
  { number: 38, nameArabic: "ص", nameEnglish: "Sad", englishMeaning: "The Letter Sad", ayahCount: 88 },
  { number: 39, nameArabic: "الزمر", nameEnglish: "Az-Zumar", englishMeaning: "The Groups", ayahCount: 75 },
  { number: 40, nameArabic: "غافر", nameEnglish: "Ghafir", englishMeaning: "The Forgiver", ayahCount: 85 },
  { number: 41, nameArabic: "فصلت", nameEnglish: "Fussilat", englishMeaning: "Explained in Detail", ayahCount: 54 },
  { number: 42, nameArabic: "الشورى", nameEnglish: "Ash-Shuraa", englishMeaning: "The Consultation", ayahCount: 53 },
  { number: 43, nameArabic: "الزخرف", nameEnglish: "Az-Zukhruf", englishMeaning: "The Ornaments of Gold", ayahCount: 89 },
  { number: 44, nameArabic: "الدخان", nameEnglish: "Ad-Dukhan", englishMeaning: "The Smoke", ayahCount: 59 },
  { number: 45, nameArabic: "الجاثية", nameEnglish: "Al-Jathiyah", englishMeaning: "The Crouching", ayahCount: 37 },
  { number: 46, nameArabic: "الأحقاف", nameEnglish: "Al-Ahqaf", englishMeaning: "The Wind-Curved Sandhills", ayahCount: 35 },
  { number: 47, nameArabic: "محمد", nameEnglish: "Muhammad", englishMeaning: "Muhammad", ayahCount: 38 },
  { number: 48, nameArabic: "الفتح", nameEnglish: "Al-Fath", englishMeaning: "The Victory", ayahCount: 29 },
  { number: 49, nameArabic: "الحجرات", nameEnglish: "Al-Hujurat", englishMeaning: "The Rooms", ayahCount: 18 },
  { number: 50, nameArabic: "ق", nameEnglish: "Qaf", englishMeaning: "The Letter Qaf", ayahCount: 45 },
  { number: 51, nameArabic: "الذاريات", nameEnglish: "Adh-Dhariyat", englishMeaning: "The Winnowing Winds", ayahCount: 60 },
  { number: 52, nameArabic: "الطور", nameEnglish: "At-Tur", englishMeaning: "The Mount", ayahCount: 49 },
  { number: 53, nameArabic: "النجم", nameEnglish: "An-Najm", englishMeaning: "The Star", ayahCount: 62 },
  { number: 54, nameArabic: "القمر", nameEnglish: "Al-Qamar", englishMeaning: "The Moon", ayahCount: 55 },
  { number: 55, nameArabic: "الرحمن", nameEnglish: "Ar-Rahman", englishMeaning: "The Beneficent", ayahCount: 78 },
  { number: 56, nameArabic: "الواقعة", nameEnglish: "Al-Waqi'ah", englishMeaning: "The Inevitable", ayahCount: 96 },
  { number: 57, nameArabic: "الحديد", nameEnglish: "Al-Hadid", englishMeaning: "The Iron", ayahCount: 29 },
  { number: 58, nameArabic: "المجادلة", nameEnglish: "Al-Mujadila", englishMeaning: "The Pleading Woman", ayahCount: 22 },
  { number: 59, nameArabic: "الحشر", nameEnglish: "Al-Hashr", englishMeaning: "The Exile", ayahCount: 24 },
  { number: 60, nameArabic: "الممتحنة", nameEnglish: "Al-Mumtahanah", englishMeaning: "She That is to be Examined", ayahCount: 13 },
  { number: 61, nameArabic: "الصف", nameEnglish: "As-Saf", englishMeaning: "The Ranks", ayahCount: 14 },
  { number: 62, nameArabic: "الجمعة", nameEnglish: "Al-Jumu'ah", englishMeaning: "The Congregation, Friday", ayahCount: 11 },
  { number: 63, nameArabic: "المنافقون", nameEnglish: "Al-Munafiqun", englishMeaning: "The Hypocrites", ayahCount: 11 },
  { number: 64, nameArabic: "التغابن", nameEnglish: "At-Taghabun", englishMeaning: "The Mutual Disillusion", ayahCount: 18 },
  { number: 65, nameArabic: "الطلاق", nameEnglish: "At-Talaq", englishMeaning: "The Divorce", ayahCount: 12 },
  { number: 66, nameArabic: "التحريم", nameEnglish: "At-Tahrim", englishMeaning: "The Prohibition", ayahCount: 12 },
  { number: 67, nameArabic: "الملك", nameEnglish: "Al-Mulk", englishMeaning: "The Sovereignty", ayahCount: 30 },
  { number: 68, nameArabic: "القلم", nameEnglish: "Al-Qalam", englishMeaning: "The Pen", ayahCount: 52 },
  { number: 69, nameArabic: "الحاقة", nameEnglish: "Al-Haqqah", englishMeaning: "The Reality", ayahCount: 52 },
  { number: 70, nameArabic: "المعارج", nameEnglish: "Al-Ma'arij", englishMeaning: "The Ascending Stairways", ayahCount: 44 },
  { number: 71, nameArabic: "نوح", nameEnglish: "Nuh", englishMeaning: "Noah", ayahCount: 28 },
  { number: 72, nameArabic: "الجن", nameEnglish: "Al-Jinn", englishMeaning: "The Jinn", ayahCount: 28 },
  { number: 73, nameArabic: "المزمل", nameEnglish: "Al-Muzzammil", englishMeaning: "The Enshrouded One", ayahCount: 20 },
  { number: 74, nameArabic: "المدثر", nameEnglish: "Al-Muddaththir", englishMeaning: "The Cloaked One", ayahCount: 56 },
  { number: 75, nameArabic: "القيامة", nameEnglish: "Al-Qiyamah", englishMeaning: "The Resurrection", ayahCount: 40 },
  { number: 76, nameArabic: "الإنسان", nameEnglish: "Al-Insan", englishMeaning: "The Man", ayahCount: 31 },
  { number: 77, nameArabic: "المرسلات", nameEnglish: "Al-Mursalat", englishMeaning: "The Emissaries", ayahCount: 50 },
  { number: 78, nameArabic: "النبأ", nameEnglish: "An-Naba", englishMeaning: "The Tidings", ayahCount: 40 },
  { number: 79, nameArabic: "النازعات", nameEnglish: "An-Nazi'at", englishMeaning: "Those who drag forth", ayahCount: 46 },
  { number: 80, nameArabic: "عبس", nameEnglish: "'Abasa", englishMeaning: "He Frowned", ayahCount: 42 },
  { number: 81, nameArabic: "التكوير", nameEnglish: "At-Takwir", englishMeaning: "The Overthrowing", ayahCount: 29 },
  { number: 82, nameArabic: "الانفطار", nameEnglish: "Al-Infitar", englishMeaning: "The Cleaving", ayahCount: 19 },
  { number: 83, nameArabic: "المطففين", nameEnglish: "Al-Mutaffifin", englishMeaning: "The Defrauding", ayahCount: 36 },
  { number: 84, nameArabic: "الانشقاق", nameEnglish: "Al-Inshiqaq", englishMeaning: "The Sundering", ayahCount: 25 },
  { number: 85, nameArabic: "البروج", nameEnglish: "Al-Buruj", englishMeaning: "The Mansions of the Stars", ayahCount: 22 },
  { number: 86, nameArabic: "الطارق", nameEnglish: "At-Tariq", englishMeaning: "The Nightcommer", ayahCount: 17 },
  { number: 87, nameArabic: "الأعلى", nameEnglish: "Al-A'la", englishMeaning: "The Most High", ayahCount: 19 },
  { number: 88, nameArabic: "الغاشية", nameEnglish: "Al-Ghashiyah", englishMeaning: "The Overwhelming", ayahCount: 26 },
  { number: 89, nameArabic: "الفجر", nameEnglish: "Al-Fajr", englishMeaning: "The Dawn", ayahCount: 30 },
  { number: 90, nameArabic: "البلد", nameEnglish: "Al-Balad", englishMeaning: "The City", ayahCount: 20 },
  { number: 91, nameArabic: "الشمس", nameEnglish: "Ash-Shams", englishMeaning: "The Sun", ayahCount: 15 },
  { number: 92, nameArabic: "الليل", nameEnglish: "Al-Layl", englishMeaning: "The Night", ayahCount: 21 },
  { number: 93, nameArabic: "الضحى", nameEnglish: "Ad-Duhaa", englishMeaning: "The Morning Hours", ayahCount: 11 },
  { number: 94, nameArabic: "الشرح", nameEnglish: "Ash-Sharh", englishMeaning: "The Relief", ayahCount: 8 },
  { number: 95, nameArabic: "التين", nameEnglish: "At-Tin", englishMeaning: "The Fig", ayahCount: 8 },
  { number: 96, nameArabic: "العلق", nameEnglish: "Al-'Alaq", englishMeaning: "The Clot", ayahCount: 19 },
  { number: 97, nameArabic: "القدر", nameEnglish: "Al-Qadr", englishMeaning: "The Power", ayahCount: 5 },
  { number: 98, nameArabic: "البينة", nameEnglish: "Al-Bayyinah", englishMeaning: "The Clear Proof", ayahCount: 8 },
  { number: 99, nameArabic: "الزلزلة", nameEnglish: "Az-Zalzalah", englishMeaning: "The Earthquake", ayahCount: 8 },
  { number: 100, nameArabic: "العاديات", nameEnglish: "Al-'Adiyat", englishMeaning: "The Courser", ayahCount: 11 },
  { number: 101, nameArabic: "القارعة", nameEnglish: "Al-Qari'ah", englishMeaning: "The Calamity", ayahCount: 11 },
  { number: 102, nameArabic: "التكاثر", nameEnglish: "At-Takathur", englishMeaning: "The Rivalry in World Increase", ayahCount: 8 },
  { number: 103, nameArabic: "العصر", nameEnglish: "Al-'Asr", englishMeaning: "The Declining Day", ayahCount: 3 },
  { number: 104, nameArabic: "الهمزة", nameEnglish: "Al-Humazah", englishMeaning: "The Traducer", ayahCount: 9 },
  { number: 105, nameArabic: "الفيل", nameEnglish: "Al-Fil", englishMeaning: "The Elephant", ayahCount: 5 },
  { number: 106, nameArabic: "قريش", nameEnglish: "Quraysh", englishMeaning: "Quraysh", ayahCount: 4 },
  { number: 107, nameArabic: "الماعون", nameEnglish: "Al-Ma'un", englishMeaning: "The Small Kindnesses", ayahCount: 7 },
  { number: 108, nameArabic: "الكوثر", nameEnglish: "Al-Kawthar", englishMeaning: "The Abundance", ayahCount: 3 },
  { number: 109, nameArabic: "الكافرون", nameEnglish: "Al-Kafirun", englishMeaning: "The Disbelievers", ayahCount: 6 },
  { number: 110, nameArabic: "النصر", nameEnglish: "An-Nasr", englishMeaning: "The Divine Support", ayahCount: 3 },
  { number: 111, nameArabic: "المسد", nameEnglish: "Al-Masad", englishMeaning: "The Palm Fibre", ayahCount: 5 },
  { number: 112, nameArabic: "الإخلاص", nameEnglish: "Al-Ikhlas", englishMeaning: "The Sincerity", ayahCount: 4 },
  { number: 113, nameArabic: "الفلق", nameEnglish: "Al-Falaq", englishMeaning: "The Daybreak", ayahCount: 5 },
  { number: 114, nameArabic: "الناس", nameEnglish: "An-Nas", englishMeaning: "Mankind", ayahCount: 6 },
];

export function getSurahByNumber(number: number): Surah | undefined {
  return SURAHS.find((s) => s.number === number);
}

export function getSurahs(): Surah[] {
  return SURAHS;
}
